### ISSUE TITLE
`npm start` doesn't work for Node v6.6.0

### ISSUE THREAD

**Issue by gvn** [mozilla/internet-health-report#1]
Getting an error after `npm i` and `npm start`:

```
  ERROR in ./src/javascripts/app.js
  Module build failed: TypeError: Path must be a string. Received undefined
      at assertPath (path.js:7:11)
      at Object.dirname (path.js:1326:5)
      at /Volumes/Nostromo/mozilla-code/internet-health-report/node_modules/babel-core/lib/transformation/file/options/option-manager.js:353:36
      at /Volumes/Nostromo/mozilla-code/internet-health-report/node_modules/babel-core/lib/transformation/file/options/option-manager.js:375:22
      at Array.map (native)
      at OptionManager.resolvePresets (/Volumes/Nostromo/mozilla-code/internet-health-report/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
      at OptionManager.mergePresets (/Volumes/Nostromo/mozilla-code/internet-health-report/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
      at OptionManager.mergeOptions (/Volumes/Nostromo/mozilla-code/internet-health-report/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
      at /Volumes/Nostromo/mozilla-code/internet-health-report/node_modules/babel-core/lib/transformation/file/options/option-manager.js:349:14
      at /Volumes/Nostromo/mozilla-code/internet-health-report/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:24
   @ multi app
  webpack: bundle is now VALID.
```

**Comment by gvn** [comment]
**Note:** This does currently work with Node v5.12.0, but should be fixed for the current version.
